server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///C:\Users\Metanet\Desktop\work\native-file-repo
        git:
#          uri: file://C:\Users\Metanet\git-local-repo
          uri: https://github.com/begrey/spring-cloud-config
          #private repository? ??
#          username: []
#          password: []
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
